version: '3.5'
volumes:
 local_postgres_data: {}
services:
 postgres:
   build: ./
   image: postgres:latest
   container_name: backend-api-db
   environment:
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_PORT: ${POSTGRES_PORT}
     POSTGRES_HOST: ${POSTGRES_HOST}
   volumes:
     - local_postgres_data:/var/lib/postgresql/data
   ports:
     - "127.0.0.1:5432:5432"
